#!/usr/bin/env bash

owner="h4m6urg1r"
username="Hamburgir"
repo="wallpapers"
# branch="main"
branch=`git branch --show-current`

embedIMG() {
	echo "![$1](/$2)"
}

genRawUrl() {
	echo "https://raw.githubusercontent.com/${owner}/${repo}/${branch}/$1/$2"
}

comment() {
	echo "<!-- $1 -->"
}

createSections() {
	for dir in */; do
		echo "1. **${dir%/}**"
		
		for file in "$dir"*; do
			# Skip if not a regular file or if it ends with .nix
			[[ -f "$file" && "${file##*.}" != "nix" ]] || continue

			filename=$(basename "$file")

			echo "	- [$filename]($(genRawUrl "$dir" "$filename"))"
			embedIMG "$filename" "$file"
			echo '		```'
			echo -n '		'
			genRawUrl "$dir" "$filename"
			echo '		```'
		done
	done
}

main() {
	echo "# $username's repository for wallpapers"
	comment "This README.md file is generated automatically any changes will be overridden"
	createSections
}

# # Dry run
# main

main > README.md
